sonar.projectKey=jusegour_formulario
sonar.organization=jusegour

sonar.sources=.

sonar.inclusions=**/*.js

sonar.exclusions=sonar.exclusions=**/*.java,coverage/**,**/*.test.js

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info